export const ADD_TODO = 'ADD_TODO';

// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Signup
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// Logout
export const LOGOUT = 'LOGOUT';

// Modal
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// Master table

export const MASTER_TABLE_FETCH_REQUEST = 'MASTER_TABLE_FETCH_REQUEST';
export const MASTER_TABLE_FETCH_SUCCESS = 'MASTER_TABLE_FETCH_SUCCESS';
export const MASTER_TABLE_FETCH_FAILURE = 'MASTER_TABLE_FETCH_FAILURE';

// Profile
export const PROFILE_FETCH_REQUEST = 'PROFILE_FETCH_REQUEST';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
export const PROFILE_FETCH_FAILURE = 'PROFILE_FETCH_FAILURE';
export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE';
export const PROFILE_DELETE_REQUEST = 'PROFILE_DELETE_REQUEST';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_FAILURE = 'PROFILE_DELETE_FAILURE';

// Employee
export const EMPLOYEE_CREATE_REQUEST = 'EMPLOYEE_CREATE_REQUEST';
export const EMPLOYEE_CREATE_SUCCESS = 'EMPLOYEE_CREATE_SUCCESS';
export const EMPLOYEE_CREATE_FAILURE = 'EMPLOYEE_CREATE_FAILURE';
export const EMPLOYEE_FETCH_REQUEST = 'EMPLOYEE_FETCH_REQUEST';
export const EMPLOYEE_FETCH_SUCCESS = 'EMPLOYEE_FETCH_SUCCESS';
export const EMPLOYEE_FETCH_FAILURE = 'EMPLOYEE_FETCH_FAILURE';
export const FILTER_EMPLOYEE = 'FILTER_EMPLOYEE';

// Project
export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_CREATE_FAILURE = 'PROJECT_CREATE_FAILURE';
export const PROJECT_FETCH_REQUEST = 'PROJECT_FETCH_REQUEST';
export const PROJECT_FETCH_SUCCESS = 'PROJECT_FETCH_SUCCESS';
export const PROJECT_FETCH_FAILURE = 'PROJECT_FETCH_FAILURE';
export const FILTER_PROJECT = 'FILTER_PROJECT';
export const SORT_PROJECT = 'SORT_PROJECT';

// Project detail
export const PROJECT_DETAIL_FETCH_REQUEST = 'PROJECT_DETAIL_FETCH_REQUEST';
export const PROJECT_DETAIL_FETCH_SUCCESS = 'PROJECT_DETAIL_FETCH_SUCCESS';
export const PROJECT_DETAIL_FETCH_FAILURE = 'PROJECT_DETAIL_FETCH_FAILURE';

// Leave
export const LEAVE_CREATE_REQUEST = 'LEAVE_CREATE_REQUEST';
export const LEAVE_CREATE_SUCCESS = 'LEAVE_CREATE_SUCCESS';
export const LEAVE_CREATE_FAILURE = 'LEAVE_CREATE_FAILURE';
export const LEAVE_FETCH_REQUEST = 'LEAVE_FETCH_REQUEST';
export const LEAVE_FETCH_SUCCESS = 'LEAVE_FETCH_SUCCESS';
export const LEAVE_FETCH_FAILURE = 'LEAVE_FETCH_FAILURE';
export const LEAVE_UPDATE_REQUEST = 'LEAVE_UPDATE_REQUEST';
export const LEAVE_UPDATE_SUCCESS = 'LEAVE_UPDATE_SUCCESS';
export const LEAVE_UPDATE_FAILURE = 'LEAVE_UPDATE_FAILURE';
export const FILTER_LEAVE = 'FILTER_LEAVE';

// Timesheet
export const TIMESHEET_FETCH_REQUEST = 'TIMESHEET_FETCH_REQUEST';
export const TIMESHHET_FETCH_SUCCESS = 'TIMESHHET_FETCH_SUCCESS';
export const TIMESHHET_FETCH_FAILURE = 'TIMESHHET_FETCH_FAILURE';

// Applicant
export const APPLICANT_FETCH_REQUEST = 'APPLICANT_FETCH_REQUEST';
export const APPLICANT_FETCH_SUCCESS = 'APPLICANT_FETCH_SUCCESS';
export const APPLICANT_FETCH_FAILURE = 'APPLICANT_FETCH_FAILURE';


// recruitment
export const RECRUITMENT_CHANGE_ACTIVE_ITEM = 'RECRUITMENT_CHANGE_ACTIVE_ITEM';
export const RECRUITMENT_FETCH_REQUEST = 'RECRUITMENT_FETCH_REQUEST';
export const RECRUITMENT_FETCH_SUCCESS = 'RECRUITMENT_FETCH_SUCCESS';
export const RECRUITMENT_FETCH_FAILURE = 'RECRUITMENT_FETCH_FAILURE';
export const RECRUITMENT_FETCH_POSITION_REQUEST = 'RECRUITMENT_FETCH_POSITION_REQUEST';
export const RECRUITMENT_FETCH_POSITION_SUCCESS = 'RECRUITMENT_FETCH_POSITION_SUCCESS';
export const RECRUITMENT_FETCH_POSITION_FAILURE = 'RECRUITMENT_FETCH_POSITION_FAILURE';
export const FILTER_RECRUITMENT = 'FILTER_RECRUITMENT';
export const SORT_RECRUITMENT = 'SORT_RECRUITMENT';
export const CHECK_RECRUITMENT_STATUS = 'CHECK_RECRUITMENT_STATUS';
export const CHANGE_RECRUITMENT_STATUS = 'CHANGE_RECRUITMENT_STATUS';
export const CLEAR_CHECKSTATUS = 'CLEAR_CHECKSTATUS';
export const RECRUITMENT_CREATE_REQUEST = 'RECRUITMENT_CREATE_REQUEST';
export const RECRUITMENT_CREATE_SUCCESS = 'RECRUITMENT_CREATE_SUCCESS';
export const RECRUITMENT_CREATE_FAILURE = 'RECRUITMENT_CREATE_FAILURE';
export const RECRUITMENT_SETDATE = 'RECRUITMENT_SETDATE';
export const RECRUITMENT_SETTIME = 'RECRUITMENT_SETTIME';
export const RECRUITMENT_UPDATE_INTERVIEW_DATETIME_REQUEST = 'RECRUITMENT_UPDATE_INTERVIEW_DATETIME_REQUEST';
export const RECRUITMENT_UPDATE_INTERVIEW_DATETIME_SUCCESS = 'RECRUITMENT_UPDATE_INTERVIEW_DATETIME_SUCCESS';
export const RECRUITMENT_UPDATE_INTERVIEW_DATETIME_FAILURE = 'RECRUITMENT_UPDATE_INTERVIEW_DATETIME_FAILURE';
export const RECRUITMENT_UPDATE_EXAM_DATETIME_REQUEST = 'RECRUITMENT_UPDATE_EXAM_DATETIME_REQUEST';
export const RECRUITMENT_UPDATE_EXAM_DATETIME_SUCCESS = 'RECRUITMENT_UPDATE_EXAM_DATETIME_SUCCESS';
export const RECRUITMENT_UPDATE_EXAM_DATETIME_FAILURE = 'RECRUITMENT_UPDATE_EXAM_DATETIME_FAILURE';
export const RECRUITMENT_UPDATE_SIGN_DATETIME_REQUEST = 'RECRUITMENT_UPDATE_SIGN_DATETIME_REQUEST';
export const RECRUITMENT_UPDATE_SIGN_DATETIME_SUCCESS = 'RECRUITMENT_UPDATE_SIGN_DATETIME_SUCCESS';
export const RECRUITMENT_UPDATE_SIGN_DATETIME_FAILURE = 'RECRUITMENT_UPDATE_SIGN_DATETIME_FAILURE';
export const RECRUITMENT_UPDATE_COMPLETE_DATETIME_REQUEST = 'RECRUITMENT_UPDATE_COMPLETE_DATETIME_REQUEST';
export const RECRUITMENT_UPDATE_COMPLETE_DATETIME_SUCCESS = 'RECRUITMENT_UPDATE_COMPLETE_DATETIME_SUCCESS';
export const RECRUITMENT_UPDATE_COMPLETE_DATETIME_FAILURE = 'RECRUITMENT_UPDATE_COMPLETE_DATETIME_FAILURE';
export const RECRUITMENT_UPDATE_REJECT_DATE_REQUEST = 'RECRUITMENT_UPDATE_REJECT_DATE_REQUEST';
export const RECRUITMENT_UPDATE_REJECT_DATE_SUCCESS = 'RECRUITMENT_UPDATE_REJECT_DATE_SUCCESS';
export const RECRUITMENT_UPDATE_REJECT_DATE_FAILURE = 'RECRUITMENT_UPDATE_REJECT_DATE_FAILURE';
export const RECRUITMENT_UPDATE_CANCEL_DATE_REQUEST = 'RECRUITMENT_UPDATE_CANCEL_DATE_REQUEST';
export const RECRUITMENT_UPDATE_CANCEL_DATE_SUCCESS = 'RECRUITMENT_UPDATE_CANCEL_DATE_SUCCESS';
export const RECRUITMENT_UPDATE_CANCEL_DATE_FAILURE = 'RECRUITMENT_UPDATE_CANCEL_DATE_FAILURE';
export const RECRUITMENT_UPDATE_BLACKLIST_DATE_REQUEST = 'RECRUITMENT_UPDATE_BLACKLIST_DATE_REQUEST';
export const RECRUITMENT_UPDATE_BLACKLIST_DATE_SUCCESS = 'RECRUITMENT_UPDATE_BLACKLIST_DATE_SUCCESS';
export const RECRUITMENT_UPDATE_BLACKLIST_DATE_FAILURE = 'RECRUITMENT_UPDATE_BLACKLIST_DATE_FAILURE';
export const RECRUITMENT_UPDATE_NOTE_REQUEST = 'RECRUITMENT_UPDATE_NOTE_REQUEST';
export const RECRUITMENT_UPDATE_NOTE_SUCCESS = 'RECRUITMENT_UPDATE_NOTE_SUCCESS';
export const RECRUITMENT_UPDATE_NOTE_FAILURE = 'RECRUITMENT_UPDATE_NOTE_FAILURE';

// recruitment profile
export const RECRUITMENT_PROFILE_FETCH_REQUEST = 'RECRUITMENT_PROFILE_FETCH_REQUEST';
export const RECRUITMENT_PROFILE_FETCH_SUCCESS = 'RECRUITMENT_PROFILE_FETCH_SUCCESS';
export const RECRUITMENT_PROFILE_FETCH_FAILURE = 'RECRUITMENT_PROFILE_FETCH_FAILURE';

